/**
 * PostClaw Database Setup Script
 *
 * Fully automated PostgreSQL database bootstrapping for the PostClaw plugin.
 * Creates the database, user, schema, indices, RLS policies, and grants.
 *
 * Usage (via OpenClaw CLI):
 *   openclaw postclaw setup [options]
 *
 * Usage (standalone):
 *   node dist/scripts/setup-db.js [options]
 *
 * Options:
 *   --admin-url <url>     Superuser connection string (default: postgres://localhost/postgres)
 *   --db-name <name>      Database name (default: memorydb)
 *   --db-user <user>      App user name (default: openclaw)
 *   --db-password <pass>  App user password (auto-generated if omitted)
 *   --skip-config         Don't auto-update openclaw.json with the new dbUrl
 */

import postgres from "postgres";
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, join } from "node:path";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function generatePassword(length = 16): string {
    const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%";
    const bytes = randomBytes(length);
    return Array.from(bytes, (b) => chars[b % chars.length]).join("");
}

function log(icon: string, msg: string) {
    console.log(`  ${icon}  ${msg}`);
}

// ─── Schema SQL (idempotent) ─────────────────────────────────────────────────

function buildSchemaSql(appUser: string, appPassword: string): string {
    // We generate the full idempotent schema inline so passwords can be injected.
    // Each statement is separated by a clear comment block.

    return `
-- ==========================================================================
-- PostClaw Schema — Auto-generated by setup-db.ts
-- ==========================================================================

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Enumerated Types (idempotent via DO block)
DO $$ BEGIN
  CREATE TYPE access_scope_enum AS ENUM ('private', 'shared', 'global');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE memory_tier_enum AS ENUM ('volatile', 'session', 'daily', 'stable', 'permanent');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE volatility_enum AS ENUM ('low', 'medium', 'high');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 3. Functions
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION enforce_immutable_ownership()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.agent_id <> OLD.agent_id THEN
        RAISE EXCEPTION 'Epistemic violation: Cannot change the original author (agent_id) of a memory.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Tables
CREATE TABLE IF NOT EXISTS agents (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    default_embedding_model VARCHAR(100) DEFAULT 'nomic-embed-text-v2-moe',
    embedding_dimensions INT DEFAULT 768,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT true,
    workspace_dir VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS agent_persona (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id VARCHAR(100) NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    access_scope access_scope_enum DEFAULT 'private',
    category VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    is_always_active BOOLEAN DEFAULT false,
    embedding vector,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(agent_id, category)
);

CREATE TABLE IF NOT EXISTS plugin_config (
    agent_id VARCHAR(100) NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    config_key VARCHAR(100) NOT NULL,
    config_value JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (agent_id, config_key)
);

CREATE TABLE IF NOT EXISTS memory_semantic (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id VARCHAR(100) NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    access_scope access_scope_enum DEFAULT 'private',
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    category VARCHAR(50),
    source_uri VARCHAR(512),
    volatility volatility_enum DEFAULT 'low',
    is_pointer BOOLEAN DEFAULT false,
    embedding vector,
    embedding_model VARCHAR(100) NOT NULL,
    token_count INT NOT NULL DEFAULT 0,
    fts_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, content)) STORED,
    confidence REAL DEFAULT 0.5,
    tier memory_tier_enum DEFAULT 'daily',
    usefulness_score REAL DEFAULT 0.0,
    injection_count INT DEFAULT 0,
    access_count INT DEFAULT 0,
    last_injected_at TIMESTAMPTZ,
    last_accessed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    is_archived BOOLEAN DEFAULT false,
    metadata JSONB DEFAULT '{}'::jsonb,
    superseded_by UUID REFERENCES memory_semantic(id) ON DELETE SET NULL,
    UNIQUE(agent_id, content_hash)
);

CREATE TABLE IF NOT EXISTS memory_episodic (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id VARCHAR(100) NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    session_id VARCHAR(100) NOT NULL,
    event_summary TEXT NOT NULL,
    event_type VARCHAR(50),
    source_uri VARCHAR(512),
    embedding vector,
    embedding_model VARCHAR(100) NOT NULL,
    token_count INT NOT NULL DEFAULT 0,
    fts_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, event_summary)) STORED,
    usefulness_score REAL DEFAULT 0.0,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS conversation_checkpoints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id VARCHAR(100) NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    session_id VARCHAR(100) NOT NULL,
    summary TEXT NOT NULL,
    active_tasks JSONB,
    token_count INT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entity_edges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id VARCHAR(100) NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    source_memory_id UUID REFERENCES memory_semantic(id) ON DELETE CASCADE,
    target_memory_id UUID REFERENCES memory_semantic(id) ON DELETE CASCADE,
    source_persona_id UUID REFERENCES agent_persona(id) ON DELETE CASCADE,
    target_persona_id UUID REFERENCES agent_persona(id) ON DELETE CASCADE,
    relationship_type VARCHAR(100) NOT NULL,
    weight REAL DEFAULT 1.0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (source_memory_id IS NOT NULL OR source_persona_id IS NOT NULL)
        AND (target_memory_id IS NOT NULL OR target_persona_id IS NOT NULL)
        AND NOT (source_memory_id IS NOT NULL AND source_memory_id = target_memory_id)
        AND NOT (source_persona_id IS NOT NULL AND source_persona_id = target_persona_id)
    ),
    UNIQUE(source_memory_id, target_memory_id, relationship_type)
);

-- 4b. Idempotent migration: add persona columns to existing entity_edges tables
ALTER TABLE entity_edges ADD COLUMN IF NOT EXISTS source_persona_id UUID REFERENCES agent_persona(id) ON DELETE CASCADE;
ALTER TABLE entity_edges ADD COLUMN IF NOT EXISTS target_persona_id UUID REFERENCES agent_persona(id) ON DELETE CASCADE;

-- Drop old CHECK constraint and re-create with persona support
-- (constraint name is auto-generated by Postgres as entity_edges_check)
ALTER TABLE entity_edges DROP CONSTRAINT IF EXISTS entity_edges_check;
ALTER TABLE entity_edges ADD CONSTRAINT entity_edges_check CHECK (
    (source_memory_id IS NOT NULL OR source_persona_id IS NOT NULL)
    AND (target_memory_id IS NOT NULL OR target_persona_id IS NOT NULL)
    AND NOT (source_memory_id IS NOT NULL AND source_memory_id = target_memory_id)
    AND NOT (source_persona_id IS NOT NULL AND source_persona_id = target_persona_id)
);

-- 5. Triggers (idempotent: drop + create)
DROP TRIGGER IF EXISTS update_memory_semantic_modtime ON memory_semantic;
CREATE TRIGGER update_memory_semantic_modtime
BEFORE UPDATE ON memory_semantic
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS trg_immutable_memory_owner ON memory_semantic;
CREATE TRIGGER trg_immutable_memory_owner
BEFORE UPDATE ON memory_semantic
FOR EACH ROW EXECUTE FUNCTION enforce_immutable_ownership();

DROP TRIGGER IF EXISTS trg_immutable_persona_owner ON agent_persona;
CREATE TRIGGER trg_immutable_persona_owner
BEFORE UPDATE ON agent_persona
FOR EACH ROW EXECUTE FUNCTION enforce_immutable_ownership();

DROP TRIGGER IF EXISTS trg_config_modtime ON plugin_config;
CREATE TRIGGER trg_config_modtime
BEFORE UPDATE ON plugin_config
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- 6. Indices
CREATE INDEX IF NOT EXISTS idx_mem_sem_agent_tier ON memory_semantic(agent_id, tier, is_archived);
CREATE INDEX IF NOT EXISTS idx_mem_sem_hash ON memory_semantic(content_hash);
CREATE INDEX IF NOT EXISTS idx_mem_epi_session ON memory_episodic(agent_id, session_id, is_archived);
CREATE INDEX IF NOT EXISTS idx_mem_sem_source_uri ON memory_semantic(source_uri) WHERE source_uri IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mem_sem_metadata ON memory_semantic USING gin (metadata);
CREATE INDEX IF NOT EXISTS idx_mem_epi_metadata ON memory_episodic USING gin (metadata);
CREATE INDEX IF NOT EXISTS idx_mem_sem_expires ON memory_semantic(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mem_sem_fts ON memory_semantic USING gin (fts_vector);
CREATE INDEX IF NOT EXISTS idx_mem_epi_fts ON memory_episodic USING gin (fts_vector);
CREATE INDEX IF NOT EXISTS idx_mem_sem_vector_nomic ON memory_semantic USING hnsw ((embedding::vector(768)) vector_cosine_ops) WHERE embedding_model = 'nomic-embed-text-v2-moe';
CREATE INDEX IF NOT EXISTS idx_mem_sem_vector_openai ON memory_semantic USING hnsw ((embedding::vector(1536)) vector_cosine_ops) WHERE embedding_model = 'text-embedding-3-small';
CREATE INDEX IF NOT EXISTS idx_edges_source ON entity_edges(source_memory_id);
CREATE INDEX IF NOT EXISTS idx_edges_target ON entity_edges(target_memory_id);
CREATE INDEX IF NOT EXISTS idx_edges_source_persona ON entity_edges(source_persona_id) WHERE source_persona_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_edges_target_persona ON entity_edges(target_persona_id) WHERE target_persona_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mem_sem_superseded ON memory_semantic(superseded_by) WHERE superseded_by IS NOT NULL;

-- 7. Row-Level Security
ALTER TABLE memory_semantic ENABLE ROW LEVEL SECURITY;
ALTER TABLE memory_episodic ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_persona ENABLE ROW LEVEL SECURITY;
ALTER TABLE plugin_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE entity_edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_checkpoints ENABLE ROW LEVEL SECURITY;

-- RLS Policies (idempotent: DROP IF EXISTS + CREATE)
-- memory_semantic
DROP POLICY IF EXISTS semantic_read ON memory_semantic;
CREATE POLICY semantic_read ON memory_semantic FOR SELECT
    USING (agent_id = current_setting('app.current_agent_id', true) OR access_scope IN ('shared', 'global'));

DROP POLICY IF EXISTS semantic_insert ON memory_semantic;
CREATE POLICY semantic_insert ON memory_semantic FOR INSERT
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS semantic_update ON memory_semantic;
CREATE POLICY semantic_update ON memory_semantic FOR UPDATE
    USING (agent_id = current_setting('app.current_agent_id', true) OR access_scope = 'global')
    WITH CHECK ((agent_id = current_setting('app.current_agent_id', true)) OR (access_scope = 'global'));

DROP POLICY IF EXISTS semantic_delete ON memory_semantic;
CREATE POLICY semantic_delete ON memory_semantic FOR DELETE
    USING (agent_id = current_setting('app.current_agent_id', true));

-- agent_persona
DROP POLICY IF EXISTS persona_read ON agent_persona;
CREATE POLICY persona_read ON agent_persona FOR SELECT
    USING (agent_id = current_setting('app.current_agent_id', true) OR access_scope IN ('shared', 'global'));

DROP POLICY IF EXISTS persona_insert ON agent_persona;
CREATE POLICY persona_insert ON agent_persona FOR INSERT
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS persona_update ON agent_persona;
CREATE POLICY persona_update ON agent_persona FOR UPDATE
    USING (agent_id = current_setting('app.current_agent_id', true) OR access_scope = 'global')
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true) OR access_scope = 'global');

DROP POLICY IF EXISTS persona_delete ON agent_persona;
CREATE POLICY persona_delete ON agent_persona FOR DELETE
    USING (agent_id = current_setting('app.current_agent_id', true));

-- plugin_config
DROP POLICY IF EXISTS config_read ON plugin_config;
CREATE POLICY config_read ON plugin_config FOR SELECT
    USING (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS config_insert ON plugin_config;
CREATE POLICY config_insert ON plugin_config FOR INSERT
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS config_update ON plugin_config;
CREATE POLICY config_update ON plugin_config FOR UPDATE
    USING (agent_id = current_setting('app.current_agent_id', true))
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS config_delete ON plugin_config;
CREATE POLICY config_delete ON plugin_config FOR DELETE
    USING (agent_id = current_setting('app.current_agent_id', true));

-- memory_episodic
DROP POLICY IF EXISTS episodic_read ON memory_episodic;
CREATE POLICY episodic_read ON memory_episodic FOR SELECT
    USING (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS episodic_insert ON memory_episodic;
CREATE POLICY episodic_insert ON memory_episodic FOR INSERT
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS episodic_update ON memory_episodic;
CREATE POLICY episodic_update ON memory_episodic FOR UPDATE
    USING (agent_id = current_setting('app.current_agent_id', true))
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS episodic_delete ON memory_episodic;
CREATE POLICY episodic_delete ON memory_episodic FOR DELETE
    USING (agent_id = current_setting('app.current_agent_id', true));

-- conversation_checkpoints
DROP POLICY IF EXISTS checkpoint_read ON conversation_checkpoints;
CREATE POLICY checkpoint_read ON conversation_checkpoints FOR SELECT
    USING (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS checkpoint_insert ON conversation_checkpoints;
CREATE POLICY checkpoint_insert ON conversation_checkpoints FOR INSERT
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS checkpoint_update ON conversation_checkpoints;
CREATE POLICY checkpoint_update ON conversation_checkpoints FOR UPDATE
    USING (agent_id = current_setting('app.current_agent_id', true))
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS checkpoint_delete ON conversation_checkpoints;
CREATE POLICY checkpoint_delete ON conversation_checkpoints FOR DELETE
    USING (agent_id = current_setting('app.current_agent_id', true));

-- entity_edges
DROP POLICY IF EXISTS edge_read ON entity_edges;
CREATE POLICY edge_read ON entity_edges FOR SELECT
    USING (
        agent_id = current_setting('app.current_agent_id', true)
        OR EXISTS (
            SELECT 1 FROM memory_semantic ms
            WHERE ms.id IN (source_memory_id, target_memory_id)
            AND ms.access_scope IN ('shared', 'global')
        )
    );

DROP POLICY IF EXISTS edge_insert ON entity_edges;
CREATE POLICY edge_insert ON entity_edges FOR INSERT
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS edge_update ON entity_edges;
CREATE POLICY edge_update ON entity_edges FOR UPDATE
    USING (agent_id = current_setting('app.current_agent_id', true))
    WITH CHECK (agent_id = current_setting('app.current_agent_id', true));

DROP POLICY IF EXISTS edge_delete ON entity_edges;
CREATE POLICY edge_delete ON entity_edges FOR DELETE
    USING (agent_id = current_setting('app.current_agent_id', true));

-- 8. App user grants
GRANT USAGE ON SCHEMA public TO ${appUser};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${appUser};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${appUser};
`;
}

// ─── Main Setup ──────────────────────────────────────────────────────────────

export interface SetupOptions {
    adminUrl?: string;
    dbName?: string;
    dbUser?: string;
    dbPassword?: string;
    skipConfig?: boolean;
}

export async function runSetup(opts: SetupOptions = {}): Promise<void> {
    const adminUrl = opts.adminUrl || "postgres://localhost/postgres";
    const dbName = opts.dbName || "memorydb";
    const appUser = opts.dbUser || "openclaw";
    const appPassword = opts.dbPassword || generatePassword();
    const skipConfig = opts.skipConfig || false;
    const adminPassword = generatePassword();

    console.log("\n🦐 PostClaw Database Setup\n");

    // ── Step 1: Connect as superuser ──────────────────────────────────────────
    let adminSql: ReturnType<typeof postgres>;
    try {
        adminSql = postgres(adminUrl, { max: 1 });
        await adminSql`SELECT 1`;
        log("✅", `Connected to Postgres as superuser`);
    } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
        log("❌", `Cannot connect to ${adminUrl}`);
        log("", `Error: ${msg}`);
        log("", `Try: openclaw postclaw setup --admin-url postgres://postgres:PASSWORD@localhost/postgres`);
        throw new Error("Superuser connection failed");
    }

    // ── Step 2: Create database ───────────────────────────────────────────────
    try {
        const exists = await adminSql`
      SELECT 1 FROM pg_database WHERE datname = ${dbName}
    `;
        if (exists.length > 0) {
            log("✅", `Database '${dbName}' already exists`);
        } else {
            // Can't use parameterized queries for CREATE DATABASE
            await adminSql.unsafe(`CREATE DATABASE ${dbName}`);
            log("✅", `Created database '${dbName}'`);
        }
    } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
        log("❌", `Failed to create database: ${msg}`);
        await adminSql.end();
        throw err;
    }

    // ── Step 3: Create app user ───────────────────────────────────────────────
    try {
        const userExists = await adminSql`
      SELECT 1 FROM pg_roles WHERE rolname = ${appUser}
    `;
        if (userExists.length > 0) {
            log("✅", `User '${appUser}' already exists`);
            // Update password to the new one
            await adminSql.unsafe(`ALTER USER ${appUser} WITH PASSWORD '${appPassword.replace(/'/g, "''")}'`);
        } else {
            await adminSql.unsafe(`CREATE USER ${appUser} WITH LOGIN PASSWORD '${appPassword.replace(/'/g, "''")}'`);
            log("✅", `Created user '${appUser}'`);
        }
        await adminSql.unsafe(`GRANT CONNECT ON DATABASE ${dbName} TO ${appUser}`);
    } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
        log("❌", `Failed to create user: ${msg}`);
        await adminSql.end();
        throw err;
    }

    // ── Step 4: Create system_admin role ──────────────────────────────────────
    try {
        const adminExists = await adminSql`
      SELECT 1 FROM pg_roles WHERE rolname = 'system_admin'
    `;
        if (adminExists.length > 0) {
            log("✅", `Role 'system_admin' already exists`);
            await adminSql.unsafe(`ALTER ROLE system_admin WITH PASSWORD '${adminPassword.replace(/'/g, "''")}'`);
        } else {
            await adminSql.unsafe(`CREATE ROLE system_admin WITH LOGIN PASSWORD '${adminPassword.replace(/'/g, "''")}'`);
            log("✅", `Created role 'system_admin'`);
        }
        await adminSql.unsafe(`ALTER ROLE system_admin BYPASSRLS`);
    } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
        log("⚠️", `system_admin role setup warning: ${msg}`);
        // Non-fatal — continue without it
    }

    await adminSql.end();

    // ── Step 5: Connect to the target database and run schema ─────────────────
    // Build a connection URL for the target database using the superuser
    const parsedAdmin = new URL(adminUrl);
    const targetUrl = `${parsedAdmin.protocol}//${parsedAdmin.username}${parsedAdmin.password ? ":" + parsedAdmin.password : ""}@${parsedAdmin.host}/${dbName}`;

    let dbSql: ReturnType<typeof postgres>;
    try {
        dbSql = postgres(targetUrl, { max: 1 });
        await dbSql`SELECT 1`;
        log("✅", `Connected to '${dbName}'`);
    } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
        log("❌", `Cannot connect to database '${dbName}': ${msg}`);
        throw err;
    }

    try {
        const schemaSql = buildSchemaSql(appUser, appPassword);
        await dbSql.unsafe(schemaSql);
        log("✅", `Schema created (6 tables, 14 indices, 18 RLS policies)`);
    } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
        log("❌", `Schema creation failed: ${msg}`);
        await dbSql.end();
        throw err;
    }

    // Grant system_admin full access
    try {
        await dbSql.unsafe(`GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO system_admin`);
        log("✅", `Granted permissions`);
    } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
        log("⚠️", `system_admin grants warning: ${msg}`);
    }

    await dbSql.end();

    // ── Step 6: Build connection string ───────────────────────────────────────
    const host = parsedAdmin.hostname || "localhost";
    const port = parsedAdmin.port || "5432";
    const appDbUrl = `postgres://${appUser}:${encodeURIComponent(appPassword)}@${host}:${port}/${dbName}`;

    // ── Step 7: Update openclaw.json ──────────────────────────────────────────
    if (!skipConfig) {
        const configPaths = [
            resolve(process.env.HOME || "~", ".openclaw", "openclaw.json"),
        ];
        for (const cfgPath of configPaths) {
            if (existsSync(cfgPath)) {
                try {
                    const raw = readFileSync(cfgPath, "utf-8");
                    const config = JSON.parse(raw);
                    if (!config.plugins) config.plugins = {};
                    if (!config.plugins.entries) config.plugins.entries = {};
                    if (!config.plugins.entries.postclaw) config.plugins.entries.postclaw = { enabled: true };
                    if (!config.plugins.entries.postclaw.config) config.plugins.entries.postclaw.config = {};
                    config.plugins.entries.postclaw.config.dbUrl = appDbUrl;
                    writeFileSync(cfgPath, JSON.stringify(config, null, 2) + "\n");
                    log("✅", `Updated ${cfgPath} with dbUrl`);
                } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
                    log("⚠️", `Could not update ${cfgPath}: ${msg}`);
                }
                break;
            }
        }
    }

    // ── Step 8: Print summary ─────────────────────────────────────────────────
    console.log("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log(`  Database:     ${dbName}`);
    console.log(`  App User:     ${appUser}`);
    console.log(`  App Password: ${appPassword}`);
    console.log(`  Admin User:   system_admin`);
    console.log(`  Admin Pass:   ${adminPassword}`);
    console.log();
    console.log(`  Connection:   ${appDbUrl}`);
    if (!skipConfig) {
        console.log();
        console.log(`  ✅ openclaw.json updated with dbUrl`);
    }
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
    console.log("  Save these credentials! They won't be shown again.\n");
}

// ─── Standalone CLI entry point ──────────────────────────────────────────────

if (require.main === module) {
    const args = process.argv.slice(2);

    function getArg(name: string): string | undefined {
        const idx = args.indexOf(name);
        if (idx === -1) return undefined;
        return args[idx + 1];
    }

    const opts: SetupOptions = {
        adminUrl: getArg("--admin-url"),
        dbName: getArg("--db-name"),
        dbUser: getArg("--db-user"),
        dbPassword: getArg("--db-password"),
        skipConfig: args.includes("--skip-config"),
    };

    runSetup(opts)
        .then(() => process.exit(0))
        .catch(() => process.exit(1));
}
